resources:
  - name: image
    type: Image
    configuration:
      registry: docker_image
      imageName: shippabledocker/sample_node_pvt
      imageTag: master
 
pipelines:
  - name: pipeline_docker
    steps:          
      - name: bash_docker
        type: Bash
        configuration:
          inputResources:
            - name: image
          integrations:
            - name: docker3
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: 
                  - 11.5.5
        execution:
          onExecute:
            - docker images
