resources:
  - name: github
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: github
  - name: image
    type: Image
    configuration:
      registry: docker_image
      imageName: shippabledocker/sample_node_pvt
      imageTag: master
 
pipelines:
  - name: pipeline_docker
    steps:          
      - name: bash_docker
        type: Bash
        configuration:
          inputResources:
            - name: image
            - name: github
          integrations:
            - name: docker3
        execution:
          onExecute:
            - docker images
