resources:
  - name: bbs
    type: GitRepo
    configuration:
      path: ~DEEPIKAB/sample_pipelines
      gitProvider: deepikaBbs
      branches:
        include: ^{{gitBranch}}$
  - name: buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 1
      externalCI: jenkins
      
      
pipelines:
  - name: pipeline
    steps:          
      - name: bash
        type: Bash
        configuration:
          inputResources:
            - name: bbs
            - name: buildInfo
          integrations:
            - name: jenkins
            - name: varsha_slack
        execution:
          onExecute:
            - printenv
            - echo "this branch is {{gitBranch}} "
            - echo "executing bash step..."
            - echo "state=$run_number" > pipeline_state.txt
            - add_pipeline_files pipeline_state.txt pipeline_state_file
            - echo "state=$run_number" > run_state.txt
            - add_run_files run_state.txt run_state_file
            - echo "state=$run_number" > cache.txt
            - restore_run_files run_state_file run_state.txt
            - restore_cache_files pipeline_state_cache cache.txt
            - add_cache_files cache.txt pipeline_state_cache
#             - mkdir /test
#             - cd /test && touch textFile.txt && echo "this is to test" > textFile.txt && cd ../
#             - add_pipeline_files /test testFolder
          onSuccess:
            - send_notification varsha_slack
      - name: bash2
        type: Bash
        configuration:
          inputSteps:
            - name: bash
        execution:
          onExecute:
            - echo "executing bash2 step..."
            - printenv
            - sleep 2m
            - restore_pipeline_files pipeline_state_file pipeline_state.txt

  
