resources:
  - name: github
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
 
pipelines:
  - name: pipeline
    steps:          
      - name: bash
        type: Bash
        configuration:
          inputResources:
            - name: github
        execution:
          onExecute:
            - echo "executing bash step..."
            - mkdir /test
            - add_pipeline_files /test abcd
      - name: bash2
        type: Bash
        configuration:
          inputSteps:
            - name: bash
        execution:
          onExecute:
            - echo "executing bash2 step..."
  
