resources:
  - name: github_demo
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
  - name: github_test
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: test123

pipelines:
  - name: pipeline_demo
    steps:          
      - name: bash_demo
        type: Bash
        configuration:
          inputResources:
            - name: github_demo
            - name: github_test
        execution:
          onExecute:
            - echo "executing bash step bash_demo..."
            - sleep 30
  
