resources:
  - name: bbs
    type: GitRepo
    configuration:
      path: ~DEEPIKAB/sample_pipelines
      gitProvider: deepikaBbs
      branches:
        include: ^{{gitBranch}}$
pipelines:
  - name: pipeline
    steps:          
      - name: bash
        type: Bash
        configuration:
          inputResources:
            - name: bbs
        execution:
          onExecute:
            - echo "this branch is {{gitBranch}} "
            - echo "executing bash step..."
            - echo "state=$run_number" > pipeline_state.txt
            - add_pipeline_files pipeline_state.txt pipeline_state_file
            - echo "state=$run_number" > cache.txt
            - add_cache_files cache.txt pipeline_state_cache
#             - mkdir /test
#             - cd /test && touch textFile.txt && echo "this is to test" > textFile.txt && cd ../
#             - add_pipeline_files /test testFolder
      - name: bash2
        type: Bash
        configuration:
          inputSteps:
            - name: bash
        execution:
          onExecute:
            - echo "executing bash2 step..."
            - printenv
            - restore_cache_files pipeline_state_cache cache.txt
            - restore_pipeline_files pipeline_state_file pipeline_state.txt
  
