resources:
  - name: github
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
pipelines:
  - name: pipeline
    steps:          
      - name: bash
        type: Bash
        configuration:
          inputResources:
            - name: github
        execution:
          onExecute:
            - echo "this branch is {{gitBranch}} "
            - echo "executing bash step..."
            - mkdir /test
            - add_pipeline_files /test testFolder
      - name: bash2
        type: Bash
        configuration:
          inputSteps:
            - name: bash
        execution:
          onExecute:
            - echo "executing bash2 step..."
            - printenv
            - mkdir /test
            - cd /test && touch textFile.txt && echo "this is to test" > textFile.txt && cd ../
            - add_pipeline_files /test testFolder
  
