resources:
  - name: github_demo
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
#   - name: github_bbs
#     type: GitRepo
#     configuration:
#       path: ~DEEPIKAB/vt1
#       gitProvider: deepikaBBS
#       branches:
#         include: master
#   - name: github_test
#     type: GitRepo
#     configuration:
#       path: deepikasl/VT2
#       gitProvider: test123

pipelines:
  - name: pipeline_demo
    steps:          
      - name: bash_demo
        type: Bash
        configuration:
          inputResources:
            - name: github_demo
#             - name: github_bbs
        execution:
          onExecute:
            - echo "executing bash step bash_demo..."
            - printenv
            - mkdir runDir
            - cd runDir
            - mkdir inDir
            - cd inDir && echo "state=$run_number" > run_state.txt
            - cd ../../
            - add_run_files "runDir/"*"/run_state" run_state_file
      - name: bash_demo_8
        type: Bash
        configuration:
          inputResources:
            - name: github_demo
          inputSteps:
            - name: bash_demo
        execution:
          onExecute:
            - echo "executing bash step bash_demo_1..."
      - name: bash_demo_9
        type: Bash
        configuration:
          inputResources:
            - name: github_demo
          inputSteps:
            - name: bash_demo_8
        execution:
          onExecute:
            - echo "executing bash step bash_demo_2..."
      
  
